"""
ScamBuster — Centralized Android Permission Catalog & Metadata (Phase 08)

Authoritative repository of Android permissions with detailed sensitivity, protection level,
AOSP release history, and privacy impact semantics.

Source: Android Open Source Project (AOSP) Android API 35 Documentation.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set

from app.security.android_permissions.categories import (
    CAT_IDENTITY,
    CAT_CONTACTS,
    CAT_PHONE,
    CAT_SMS,
    CAT_LOCATION,
    CAT_CAMERA,
    CAT_MICROPHONE,
    CAT_STORAGE_FILES,
    CAT_MEDIA,
    CAT_CALENDAR,
    CAT_SENSORS,
    CAT_BLUETOOTH,
    CAT_NETWORK,
    CAT_NOTIFICATIONS,
    CAT_ACCESSIBILITY,
    CAT_OVERLAY,
    CAT_DEVICE_ADMIN,
    CAT_INSTALLATION,
    CAT_SYSTEM_CONTROL,
    CAT_UNKNOWN,
    SENSITIVITY_LOW,
    SENSITIVITY_MEDIUM,
    SENSITIVITY_HIGH,
    SENSITIVITY_VERY_HIGH,
    PROTECTION_NORMAL,
    PROTECTION_DANGEROUS,
    PROTECTION_SPECIAL,
    PROTECTION_SIGNATURE,
    PROTECTION_UNKNOWN,
)
from app.security.android_permissions.version import (
    is_runtime_permission_at_target,
    parse_sdk_version,
)


@dataclass
class AndroidPermissionMetadata:
    permission: str
    short_name: str
    category: str
    sensitivity: str
    protection_level: str
    runtime_permission: bool
    added_api_level: int
    deprecated_api_level: Optional[int]
    description: str
    privacy_impact: List[str] = field(default_factory=list)
    user_consent_required: bool = False
    why_it_matters: str = ""

    def to_dict(self) -> Dict[str, any]:
        return {
            "permission": self.permission,
            "short_name": self.short_name,
            "category": self.category,
            "sensitivity": self.sensitivity,
            "protection_level": self.protection_level,
            "runtime_permission": self.runtime_permission,
            "added_api_level": self.added_api_level,
            "deprecated_api_level": self.deprecated_api_level,
            "description": self.description,
            "privacy_impact": self.privacy_impact,
            "user_consent_required": self.user_consent_required,
            "why_it_matters": self.why_it_matters,
        }


# --- Master AOSP Permission Catalog ---

PERMISSION_CATALOG: Dict[str, AndroidPermissionMetadata] = {
    # === SMS & Messaging (VERY_HIGH Sensitivity) ===
    "android.permission.READ_SMS": AndroidPermissionMetadata(
        permission="android.permission.READ_SMS",
        short_name="READ_SMS",
        category=CAT_SMS,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to read SMS messages stored on phone or SIM card.",
        privacy_impact=["sms_inbox_access", "otp_interception_risk", "private_messages"],
        user_consent_required=True,
        why_it_matters="SMS messages often contain sensitive two-factor authentication (2FA) OTP codes and private correspondence.",
    ),
    "android.permission.RECEIVE_SMS": AndroidPermissionMetadata(
        permission="android.permission.RECEIVE_SMS",
        short_name="RECEIVE_SMS",
        category=CAT_SMS,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to monitor and receive incoming SMS messages in real-time.",
        privacy_impact=["real_time_sms_monitoring", "otp_theft", "sms_filtering"],
        user_consent_required=True,
        why_it_matters="Can intercept incoming 2FA codes before or while the user sees them.",
    ),
    "android.permission.SEND_SMS": AndroidPermissionMetadata(
        permission="android.permission.SEND_SMS",
        short_name="SEND_SMS",
        category=CAT_SMS,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to send SMS messages directly without user interaction.",
        privacy_impact=["toll_fraud", "premium_rate_sms", "silent_dispatch"],
        user_consent_required=True,
        why_it_matters="Can send premium-rate SMS messages that incur unexpected financial charges on the mobile bill.",
    ),
    "android.permission.RECEIVE_MMS": AndroidPermissionMetadata(
        permission="android.permission.RECEIVE_MMS",
        short_name="RECEIVE_MMS",
        category=CAT_SMS,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to monitor incoming MMS messages.",
        privacy_impact=["mms_monitoring", "multimedia_interception"],
        user_consent_required=True,
        why_it_matters="Allows inspection of incoming multimedia messages.",
    ),
    "android.permission.RECEIVE_WAP_PUSH": AndroidPermissionMetadata(
        permission="android.permission.RECEIVE_WAP_PUSH",
        short_name="RECEIVE_WAP_PUSH",
        category=CAT_SMS,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to receive WAP push dispatches.",
        privacy_impact=["wap_push_monitoring"],
        user_consent_required=True,
        why_it_matters="Legacy carrier messaging channel occasionally abused for phishing links.",
    ),

    # === Contacts & Identity (HIGH Sensitivity) ===
    "android.permission.READ_CONTACTS": AndroidPermissionMetadata(
        permission="android.permission.READ_CONTACTS",
        short_name="READ_CONTACTS",
        category=CAT_CONTACTS,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to read the entire user address book.",
        privacy_impact=["address_book_harvesting", "social_graph_profiling"],
        user_consent_required=True,
        why_it_matters="Exposes names, phone numbers, email addresses, and relationship structures of friends and family.",
    ),
    "android.permission.WRITE_CONTACTS": AndroidPermissionMetadata(
        permission="android.permission.WRITE_CONTACTS",
        short_name="WRITE_CONTACTS",
        category=CAT_CONTACTS,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to modify or delete contacts in user address book.",
        privacy_impact=["contact_modification", "contact_tampering"],
        user_consent_required=True,
        why_it_matters="Can alter contact records or add deceptive numbers.",
    ),
    "android.permission.GET_ACCOUNTS": AndroidPermissionMetadata(
        permission="android.permission.GET_ACCOUNTS",
        short_name="GET_ACCOUNTS",
        category=CAT_IDENTITY,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows access to the list of synchronized accounts on the device.",
        privacy_impact=["email_account_enumeration", "identity_tracking"],
        user_consent_required=True,
        why_it_matters="Reveals primary Google, social media, and corporate email accounts configured on the device.",
    ),

    # === Location (HIGH Sensitivity) ===
    "android.permission.ACCESS_FINE_LOCATION": AndroidPermissionMetadata(
        permission="android.permission.ACCESS_FINE_LOCATION",
        short_name="ACCESS_FINE_LOCATION",
        category=CAT_LOCATION,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to access precise GPS geographic coordinates.",
        privacy_impact=["precise_geographic_tracking", "physical_movement_profiling"],
        user_consent_required=True,
        why_it_matters="Can pin exact physical location down to a few meters (home, workplace, travel habits).",
    ),
    "android.permission.ACCESS_COARSE_LOCATION": AndroidPermissionMetadata(
        permission="android.permission.ACCESS_COARSE_LOCATION",
        short_name="ACCESS_COARSE_LOCATION",
        category=CAT_LOCATION,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to access approximate location derived from network towers and Wi-Fi.",
        privacy_impact=["city_neighborhood_tracking"],
        user_consent_required=True,
        why_it_matters="Provides neighborhood-level tracking without full GPS lock.",
    ),
    "android.permission.ACCESS_BACKGROUND_LOCATION": AndroidPermissionMetadata(
        permission="android.permission.ACCESS_BACKGROUND_LOCATION",
        short_name="ACCESS_BACKGROUND_LOCATION",
        category=CAT_LOCATION,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=29,  # Android 10
        deprecated_api_level=None,
        description="Allows application to track physical location continuously even while closed or in background.",
        privacy_impact=["continuous_background_tracking", "persistent_geofencing"],
        user_consent_required=True,
        why_it_matters="Monitors user movement 24/7 without active foreground application engagement.",
    ),

    # === Sensors & Recording (HIGH Sensitivity) ===
    "android.permission.CAMERA": AndroidPermissionMetadata(
        permission="android.permission.CAMERA",
        short_name="CAMERA",
        category=CAT_CAMERA,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to capture photos and video streams from front and rear cameras.",
        privacy_impact=["image_capture", "video_recording", "visual_surveillance"],
        user_consent_required=True,
        why_it_matters="Direct access to physical visual surroundings and facial imagery.",
    ),
    "android.permission.RECORD_AUDIO": AndroidPermissionMetadata(
        permission="android.permission.RECORD_AUDIO",
        short_name="RECORD_AUDIO",
        category=CAT_MICROPHONE,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to capture audio from device microphone.",
        privacy_impact=["audio_recording", "room_eavesdropping", "voice_surveillance"],
        user_consent_required=True,
        why_it_matters="Allows listening to spoken private conversations, ambient sounds, and calls.",
    ),
    "android.permission.BODY_SENSORS": AndroidPermissionMetadata(
        permission="android.permission.BODY_SENSORS",
        short_name="BODY_SENSORS",
        category=CAT_SENSORS,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=20,
        deprecated_api_level=None,
        description="Allows access to heart rate and biometric sensors.",
        privacy_impact=["health_biometrics", "physical_condition_tracking"],
        user_consent_required=True,
        why_it_matters="Exposes physiological data such as pulse, sleep, and heart rate.",
    ),
    "android.permission.ACTIVITY_RECOGNITION": AndroidPermissionMetadata(
        permission="android.permission.ACTIVITY_RECOGNITION",
        short_name="ACTIVITY_RECOGNITION",
        category=CAT_SENSORS,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=29,
        deprecated_api_level=None,
        description="Allows recognizing physical activities such as walking, driving, or biking.",
        privacy_impact=["physical_activity_profiling"],
        user_consent_required=True,
        why_it_matters="Infers lifestyle and physical movement patterns.",
    ),

    # === Phone & Call State (HIGH Sensitivity) ===
    "android.permission.READ_PHONE_STATE": AndroidPermissionMetadata(
        permission="android.permission.READ_PHONE_STATE",
        short_name="READ_PHONE_STATE",
        category=CAT_PHONE,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows read access to phone state, cellular network info, and ongoing call status.",
        privacy_impact=["device_identifier_harvesting", "call_status_monitoring", "carrier_tracking"],
        user_consent_required=True,
        why_it_matters="Can reveal persistent cellular identifiers (IMSI, phone number) and ongoing call activities.",
    ),
    "android.permission.CALL_PHONE": AndroidPermissionMetadata(
        permission="android.permission.CALL_PHONE",
        short_name="CALL_PHONE",
        category=CAT_PHONE,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to initiate phone calls without passing through the dialer UI.",
        privacy_impact=["toll_fraud", "unsolicited_calling"],
        user_consent_required=True,
        why_it_matters="Can initiate phone calls in the background without user confirmation.",
    ),
    "android.permission.READ_CALL_LOG": AndroidPermissionMetadata(
        permission="android.permission.READ_CALL_LOG",
        short_name="READ_CALL_LOG",
        category=CAT_PHONE,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=16,
        deprecated_api_level=None,
        description="Allows application to read the incoming and outgoing phone call history.",
        privacy_impact=["call_history_harvesting", "communication_graph_analysis"],
        user_consent_required=True,
        why_it_matters="Contains full records of who the user communicates with, call durations, and timestamps.",
    ),
    "android.permission.WRITE_CALL_LOG": AndroidPermissionMetadata(
        permission="android.permission.WRITE_CALL_LOG",
        short_name="WRITE_CALL_LOG",
        category=CAT_PHONE,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=16,
        deprecated_api_level=None,
        description="Allows application to modify or delete the device call log.",
        privacy_impact=["call_history_tampering"],
        user_consent_required=True,
        why_it_matters="Can cover tracks of unauthorized background calls by deleting log entries.",
    ),
    "android.permission.PROCESS_OUTGOING_CALLS": AndroidPermissionMetadata(
        permission="android.permission.PROCESS_OUTGOING_CALLS",
        short_name="PROCESS_OUTGOING_CALLS",
        category=CAT_PHONE,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=29,  # Deprecated in favor of CallScreeningService
        description="Allows application to monitor, redirect, or abort outgoing calls.",
        privacy_impact=["call_interception", "call_redirection"],
        user_consent_required=True,
        why_it_matters="Can redirect calls away from legitimate numbers (e.g. intercepting bank helpline calls).",
    ),

    # === Storage & Media (MEDIUM to HIGH Sensitivity) ===
    "android.permission.READ_EXTERNAL_STORAGE": AndroidPermissionMetadata(
        permission="android.permission.READ_EXTERNAL_STORAGE",
        short_name="READ_EXTERNAL_STORAGE",
        category=CAT_STORAGE_FILES,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=16,
        deprecated_api_level=33,  # Superseded by granular media on Android 13
        description="Allows application to read files from external shared storage.",
        privacy_impact=["document_access", "stored_media_harvesting"],
        user_consent_required=True,
        why_it_matters="Can access documents, downloaded files, and photos stored on device storage.",
    ),
    "android.permission.WRITE_EXTERNAL_STORAGE": AndroidPermissionMetadata(
        permission="android.permission.WRITE_EXTERNAL_STORAGE",
        short_name="WRITE_EXTERNAL_STORAGE",
        category=CAT_STORAGE_FILES,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=4,
        deprecated_api_level=29,  # Scoped storage limits write access
        description="Allows application to write files to external shared storage.",
        privacy_impact=["file_modification", "arbitrary_file_creation"],
        user_consent_required=True,
        why_it_matters="Allows saving or modifying files in shared folders.",
    ),
    "android.permission.MANAGE_EXTERNAL_STORAGE": AndroidPermissionMetadata(
        permission="android.permission.MANAGE_EXTERNAL_STORAGE",
        short_name="MANAGE_EXTERNAL_STORAGE",
        category=CAT_STORAGE_FILES,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_SPECIAL,
        runtime_permission=False,
        added_api_level=30,  # Android 11
        deprecated_api_level=None,
        description="Broad access to all shared storage across entire filesystem, bypassing Scoped Storage.",
        privacy_impact=["full_filesystem_access", "all_documents_exposure"],
        user_consent_required=True,
        why_it_matters="Grants unrestricted access to nearly all files on the device filesystem.",
    ),
    "android.permission.READ_MEDIA_IMAGES": AndroidPermissionMetadata(
        permission="android.permission.READ_MEDIA_IMAGES",
        short_name="READ_MEDIA_IMAGES",
        category=CAT_MEDIA,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=33,  # Android 13
        deprecated_api_level=None,
        description="Granular access to all image files in device photo galleries.",
        privacy_impact=["photo_gallery_access", "personal_images_exposure"],
        user_consent_required=True,
        why_it_matters="Allows viewing all personal photos and saved graphics.",
    ),
    "android.permission.READ_MEDIA_VIDEO": AndroidPermissionMetadata(
        permission="android.permission.READ_MEDIA_VIDEO",
        short_name="READ_MEDIA_VIDEO",
        category=CAT_MEDIA,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=33,  # Android 13
        deprecated_api_level=None,
        description="Granular access to all video recordings on device.",
        privacy_impact=["video_gallery_access"],
        user_consent_required=True,
        why_it_matters="Allows viewing all personal video recordings.",
    ),
    "android.permission.READ_MEDIA_AUDIO": AndroidPermissionMetadata(
        permission="android.permission.READ_MEDIA_AUDIO",
        short_name="READ_MEDIA_AUDIO",
        category=CAT_MEDIA,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=33,  # Android 13
        deprecated_api_level=None,
        description="Granular access to audio music and podcast files.",
        privacy_impact=["audio_library_access"],
        user_consent_required=True,
        why_it_matters="Accesses saved music and audio recordings.",
    ),

    # === Calendar (MEDIUM Sensitivity) ===
    "android.permission.READ_CALENDAR": AndroidPermissionMetadata(
        permission="android.permission.READ_CALENDAR",
        short_name="READ_CALENDAR",
        category=CAT_CALENDAR,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to read user calendar events and schedule.",
        privacy_impact=["schedule_profiling", "meeting_details_exposure"],
        user_consent_required=True,
        why_it_matters="Exposes personal schedule, attendees, locations, and appointments.",
    ),
    "android.permission.WRITE_CALENDAR": AndroidPermissionMetadata(
        permission="android.permission.WRITE_CALENDAR",
        short_name="WRITE_CALENDAR",
        category=CAT_CALENDAR,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to add or modify calendar appointments.",
        privacy_impact=["calendar_modification"],
        user_consent_required=True,
        why_it_matters="Can inject events or modify calendar reminders.",
    ),

    # === High-Privilege & System Capabilities (VERY_HIGH Sensitivity) ===
    "android.permission.BIND_ACCESSIBILITY_SERVICE": AndroidPermissionMetadata(
        permission="android.permission.BIND_ACCESSIBILITY_SERVICE",
        short_name="BIND_ACCESSIBILITY_SERVICE",
        category=CAT_ACCESSIBILITY,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_SIGNATURE,  # Special system permission
        runtime_permission=False,
        added_api_level=16,
        deprecated_api_level=None,
        description="Must be required by an AccessibilityService to ensure only system can bind to it.",
        privacy_impact=["ui_keystroke_inspection", "full_screen_content_reading", "automated_ui_actions"],
        user_consent_required=True,
        why_it_matters="Accessibility capabilities allow observing all on-screen content (passwords, PINs, chats) and performing automated clicks.",
    ),
    "android.permission.SYSTEM_ALERT_WINDOW": AndroidPermissionMetadata(
        permission="android.permission.SYSTEM_ALERT_WINDOW",
        short_name="SYSTEM_ALERT_WINDOW",
        category=CAT_OVERLAY,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_SPECIAL,
        runtime_permission=False,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows an application to display overlay windows on top of all other apps.",
        privacy_impact=["screen_overlay_phishing", "clickjacking", "deceptive_ui_interception"],
        user_consent_required=True,
        why_it_matters="Can draw fake login windows on top of legitimate banking or shopping apps (tapjacking/clickjacking).",
    ),
    "android.permission.REQUEST_INSTALL_PACKAGES": AndroidPermissionMetadata(
        permission="android.permission.REQUEST_INSTALL_PACKAGES",
        short_name="REQUEST_INSTALL_PACKAGES",
        category=CAT_INSTALLATION,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_SPECIAL,
        runtime_permission=False,
        added_api_level=26,  # Android 8.0
        deprecated_api_level=None,
        description="Allows application to request installing other APK packages from outside Play Store.",
        privacy_impact=["dropper_payload_installation", "unverified_software_execution"],
        user_consent_required=True,
        why_it_matters="Can download and prompt to install secondary applications without Play Store security verification.",
    ),
    "android.permission.BIND_DEVICE_ADMIN": AndroidPermissionMetadata(
        permission="android.permission.BIND_DEVICE_ADMIN",
        short_name="BIND_DEVICE_ADMIN",
        category=CAT_DEVICE_ADMIN,
        sensitivity=SENSITIVITY_VERY_HIGH,
        protection_level=PROTECTION_SIGNATURE,
        runtime_permission=False,
        added_api_level=8,
        deprecated_api_level=None,
        description="Must be required by a device administration receiver to ensure only system can interact.",
        privacy_impact=["device_lockout", "password_reset_authority", "remote_wipe", "uninstall_prevention"],
        user_consent_required=True,
        why_it_matters="Can prevent uninstallation, enforce lock screen policies, or remotely wipe device data.",
    ),
    "android.permission.POST_NOTIFICATIONS": AndroidPermissionMetadata(
        permission="android.permission.POST_NOTIFICATIONS",
        short_name="POST_NOTIFICATIONS",
        category=CAT_NOTIFICATIONS,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_DANGEROUS,
        runtime_permission=True,
        added_api_level=33,  # Android 13
        deprecated_api_level=None,
        description="Allows application to post notification badges and alerts in system shade.",
        privacy_impact=["unsolicited_notifications", "phishing_alerts"],
        user_consent_required=True,
        why_it_matters="Controls whether app can send push alerts to the notification center.",
    ),
    "android.permission.PACKAGE_USAGE_STATS": AndroidPermissionMetadata(
        permission="android.permission.PACKAGE_USAGE_STATS",
        short_name="PACKAGE_USAGE_STATS",
        category=CAT_SYSTEM_CONTROL,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_SPECIAL,
        runtime_permission=False,
        added_api_level=21,
        deprecated_api_level=None,
        description="Allows application to observe which apps the user opens and for how long.",
        privacy_impact=["application_usage_profiling", "active_app_monitoring"],
        user_consent_required=True,
        why_it_matters="Tracks which applications the user uses and can trigger targeted overlays when banking apps launch.",
    ),
    "android.permission.QUERY_ALL_PACKAGES": AndroidPermissionMetadata(
        permission="android.permission.QUERY_ALL_PACKAGES",
        short_name="QUERY_ALL_PACKAGES",
        category=CAT_SYSTEM_CONTROL,
        sensitivity=SENSITIVITY_HIGH,
        protection_level=PROTECTION_NORMAL,  # Play Store policy restricted
        runtime_permission=False,
        added_api_level=30,  # Android 11
        deprecated_api_level=None,
        description="Allows querying the full inventory of all installed applications on the device.",
        privacy_impact=["installed_software_profiling", "target_app_detection"],
        user_consent_required=False,
        why_it_matters="Discovers every application installed on the device (banks, crypto wallets, dating apps).",
    ),
    "android.permission.RECEIVE_BOOT_COMPLETED": AndroidPermissionMetadata(
        permission="android.permission.RECEIVE_BOOT_COMPLETED",
        short_name="RECEIVE_BOOT_COMPLETED",
        category=CAT_SYSTEM_CONTROL,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_NORMAL,
        runtime_permission=False,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to start background services immediately after device finishes booting.",
        privacy_impact=["background_persistence", "autostart"],
        user_consent_required=False,
        why_it_matters="Allows the application to run automatically in the background every time the device restarts.",
    ),
    "android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS": AndroidPermissionMetadata(
        permission="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
        short_name="REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
        category=CAT_SYSTEM_CONTROL,
        sensitivity=SENSITIVITY_MEDIUM,
        protection_level=PROTECTION_NORMAL,
        runtime_permission=False,
        added_api_level=23,
        deprecated_api_level=None,
        description="Allows application to request exemption from Android Doze background power-saving limits.",
        privacy_impact=["unrestricted_background_execution"],
        user_consent_required=True,
        why_it_matters="Prevents Android system from putting background services to sleep.",
    ),

    # === Network & Standard (LOW Sensitivity) ===
    "android.permission.INTERNET": AndroidPermissionMetadata(
        permission="android.permission.INTERNET",
        short_name="INTERNET",
        category=CAT_NETWORK,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_NORMAL,
        runtime_permission=False,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to open network sockets to the internet.",
        privacy_impact=["data_transmission", "ad_loading"],
        user_consent_required=False,
        why_it_matters="Standard permission used by almost all online apps; enables network data exchange.",
    ),
    "android.permission.ACCESS_NETWORK_STATE": AndroidPermissionMetadata(
        permission="android.permission.ACCESS_NETWORK_STATE",
        short_name="ACCESS_NETWORK_STATE",
        category=CAT_NETWORK,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_NORMAL,
        runtime_permission=False,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to inspect connectivity status (Wi-Fi, cellular, offline).",
        privacy_impact=["network_connectivity_monitoring"],
        user_consent_required=False,
        why_it_matters="Standard utility permission to check if device is connected to the internet.",
    ),
    "android.permission.ACCESS_WIFI_STATE": AndroidPermissionMetadata(
        permission="android.permission.ACCESS_WIFI_STATE",
        short_name="ACCESS_WIFI_STATE",
        category=CAT_NETWORK,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_NORMAL,
        runtime_permission=False,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to view information about Wi-Fi networking.",
        privacy_impact=["wifi_ssid_monitoring"],
        user_consent_required=False,
        why_it_matters="Checks Wi-Fi status and connection speed.",
    ),
    "android.permission.VIBRATE": AndroidPermissionMetadata(
        permission="android.permission.VIBRATE",
        short_name="VIBRATE",
        category=CAT_SYSTEM_CONTROL,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_NORMAL,
        runtime_permission=False,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows access to device vibration motor.",
        privacy_impact=[],
        user_consent_required=False,
        why_it_matters="Hardware haptic feedback.",
    ),
    "android.permission.WAKE_LOCK": AndroidPermissionMetadata(
        permission="android.permission.WAKE_LOCK",
        short_name="WAKE_LOCK",
        category=CAT_SYSTEM_CONTROL,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_NORMAL,
        runtime_permission=False,
        added_api_level=1,
        deprecated_api_level=None,
        description="Allows application to keep processor awake to finish background tasks.",
        privacy_impact=["battery_drain"],
        user_consent_required=False,
        why_it_matters="Prevents CPU from entering deep sleep.",
    ),
}

# High-impact capability set (warrants prioritized user visibility)
HIGH_IMPACT_PERMISSIONS: Set[str] = {
    "android.permission.BIND_ACCESSIBILITY_SERVICE",
    "android.permission.SYSTEM_ALERT_WINDOW",
    "android.permission.BIND_DEVICE_ADMIN",
    "android.permission.REQUEST_INSTALL_PACKAGES",
    "android.permission.MANAGE_EXTERNAL_STORAGE",
    "android.permission.ACCESS_BACKGROUND_LOCATION",
    "android.permission.READ_SMS",
    "android.permission.RECEIVE_SMS",
    "android.permission.SEND_SMS",
    "android.permission.PROCESS_OUTGOING_CALLS",
    "android.permission.PACKAGE_USAGE_STATS",
}


def get_permission_metadata(perm: str, target_sdk: Optional[int] = None) -> AndroidPermissionMetadata:
    """
    Retrieve authoritative metadata for a permission string.
    If permission is unrecognized, returns an UNKNOWN category descriptor with objective wording.
    """
    clean = perm.strip()
    if clean in PERMISSION_CATALOG:
        meta = PERMISSION_CATALOG[clean]
        # Adjust runtime permission requirement if target SDK is known
        is_runtime = is_runtime_permission_at_target(
            clean,
            target_sdk,
            meta.protection_level == PROTECTION_DANGEROUS
        )
        return AndroidPermissionMetadata(
            permission=meta.permission,
            short_name=meta.short_name,
            category=meta.category,
            sensitivity=meta.sensitivity,
            protection_level=meta.protection_level,
            runtime_permission=is_runtime,
            added_api_level=meta.added_api_level,
            deprecated_api_level=meta.deprecated_api_level,
            description=meta.description,
            privacy_impact=meta.privacy_impact,
            user_consent_required=meta.user_consent_required,
            why_it_matters=meta.why_it_matters,
        )

    # Clean short display name
    short = clean.split(".")[-1] if "." in clean else clean

    return AndroidPermissionMetadata(
        permission=clean,
        short_name=short,
        category=CAT_UNKNOWN,
        sensitivity=SENSITIVITY_LOW,
        protection_level=PROTECTION_UNKNOWN,
        runtime_permission=False,
        added_api_level=0,
        deprecated_api_level=None,
        description="Permission was not recognized by the current permission catalog.",
        privacy_impact=[],
        user_consent_required=False,
        why_it_matters="Custom, third-party library, or vendor-defined permission not part of standard AOSP definitions.",
    )


def is_high_impact_permission(perm: str) -> bool:
    """Return True if permission can grant elevated system control or deep private data access."""
    return perm.strip() in HIGH_IMPACT_PERMISSIONS
