"""
ScamBuster — Android Permission Categories & Privacy Taxonomy (Phase 08)

Defines canonical functional categories and sensitivity tiers for Android permissions.
Adheres to authoritative Android Open Source Project (AOSP) capability models.
"""

# Canonical Functional Categories
CAT_IDENTITY = "IDENTITY"
CAT_CONTACTS = "CONTACTS"
CAT_PHONE = "PHONE"
CAT_SMS = "SMS"
CAT_LOCATION = "LOCATION"
CAT_CAMERA = "CAMERA"
CAT_MICROPHONE = "MICROPHONE"
CAT_STORAGE_FILES = "STORAGE_FILES"
CAT_MEDIA = "MEDIA"
CAT_CALENDAR = "CALENDAR"
CAT_SENSORS = "SENSORS"
CAT_BLUETOOTH = "BLUETOOTH"
CAT_NETWORK = "NETWORK"
CAT_NOTIFICATIONS = "NOTIFICATIONS"
CAT_ACCESSIBILITY = "ACCESSIBILITY"
CAT_OVERLAY = "OVERLAY"
CAT_DEVICE_ADMIN = "DEVICE_ADMIN"
CAT_INSTALLATION = "INSTALLATION"
CAT_SYSTEM_CONTROL = "SYSTEM_CONTROL"
CAT_UNKNOWN = "UNKNOWN"

ALL_PERMISSION_CATEGORIES = [
    CAT_IDENTITY,
    CAT_CONTACTS,
    CAT_PHONE,
    CAT_SMS,
    CAT_LOCATION,
    CAT_CAMERA,
    CAT_MICROPHONE,
    CAT_STORAGE_FILES,
    CAT_MEDIA,
    CAT_CALENDAR,
    CAT_SENSORS,
    CAT_BLUETOOTH,
    CAT_NETWORK,
    CAT_NOTIFICATIONS,
    CAT_ACCESSIBILITY,
    CAT_OVERLAY,
    CAT_DEVICE_ADMIN,
    CAT_INSTALLATION,
    CAT_SYSTEM_CONTROL,
    CAT_UNKNOWN,
]

# Privacy Sensitivity Tiers (Privacy Impact, NOT Malware probability)
SENSITIVITY_LOW = "LOW"
SENSITIVITY_MEDIUM = "MEDIUM"
SENSITIVITY_HIGH = "HIGH"
SENSITIVITY_VERY_HIGH = "VERY_HIGH"

ALL_SENSITIVITIES = [
    SENSITIVITY_LOW,
    SENSITIVITY_MEDIUM,
    SENSITIVITY_HIGH,
    SENSITIVITY_VERY_HIGH,
]

# AOSP Protection Levels
PROTECTION_NORMAL = "normal"
PROTECTION_DANGEROUS = "dangerous"
PROTECTION_SIGNATURE = "signature"
PROTECTION_SPECIAL = "special"
PROTECTION_UNKNOWN = "unknown"
