"""
ScamBuster — Mock Threat Intelligence Provider for Testing (Phase 11)

Provides a fully controllable provider for unit tests, security tests, and CI:
- Simulates timeouts, 429 rate-limiting, 500 server errors, malformed responses
- Programmable preset reports for any indicator value
- Safe zero-network testing harness
"""

import asyncio
from typing import Dict, Optional, Set

from app.intelligence.models import (
    FreshnessState,
    IndicatorType,
    IntelligenceStatus,
    IntelligenceVerdict,
    ThreatIndicator,
    ThreatIntelligenceReport,
)
from app.intelligence.providers.base import BaseThreatIntelProvider


class MockThreatIntelProvider(BaseThreatIntelProvider):
    def __init__(
        self,
        name: str = "mock-threat-intel",
        provider_id: Optional[str] = None,
        default_verdict: IntelligenceVerdict = IntelligenceVerdict.UNKNOWN,
        confidence: float = 0.7,
        configured: bool = True,
        timeout_seconds: float = 2.0,
        rate_limit_rpm: int = 100,
        simulate_timeout: bool = False,
        simulate_rate_limit: bool = False,
        simulate_error: bool = False,
        simulate_malformed: bool = False,
        delay_seconds: float = 0.0,
        preset_reports: Optional[Dict[str, ThreatIntelligenceReport]] = None,
        **kwargs,
    ):
        super().__init__(timeout_seconds=timeout_seconds, max_retries=1, rate_limit_rpm=rate_limit_rpm)
        self._name = provider_id or name
        self.default_verdict = default_verdict
        self.confidence = confidence
        self._configured = configured
        self.simulate_timeout = simulate_timeout
        self.simulate_rate_limit = simulate_rate_limit
        self.simulate_error = simulate_error
        self.simulate_malformed = simulate_malformed
        self.delay_seconds = delay_seconds
        self.preset_reports = preset_reports or {}
        self.request_count = 0

    @property
    def name(self) -> str:
        return self._name

    @property
    def supported_indicator_types(self) -> Set[IndicatorType]:
        return {
            IndicatorType.URL,
            IndicatorType.DOMAIN,
            IndicatorType.IP,
            IndicatorType.FILE_HASH,
            IndicatorType.PHONE,
            IndicatorType.EMAIL,
        }

    def is_configured(self) -> bool:
        return self._configured

    def set_preset(self, indicator_val: str, report: ThreatIntelligenceReport) -> None:
        self.preset_reports[indicator_val.strip().lower()] = report

    async def _execute_lookup(self, indicator: ThreatIndicator) -> ThreatIntelligenceReport:
        self.request_count += 1
        if self.delay_seconds > 0:
            await asyncio.sleep(self.delay_seconds)

        if self.simulate_timeout:
            await asyncio.sleep(self.timeout_seconds + 0.1)
            raise asyncio.TimeoutError("Simulated provider timeout")

        if self.simulate_rate_limit:
            raise RuntimeError("HTTP 429 Too Many Requests: Rate limit exceeded")

        if self.simulate_error:
            raise RuntimeError("HTTP 500 Internal Server Error from upstream provider")

        if self.simulate_malformed:
            raise ValueError("Malformed response received: unexpected schema")

        # Check explicit presets by normalized or raw value
        norm_key = indicator.normalized_value.lower()
        raw_key = indicator.value.lower()

        if norm_key in self.preset_reports:
            p = self.preset_reports[norm_key]
            p.indicator = indicator
            p.provider = self._name
            return p

        if raw_key in self.preset_reports:
            p = self.preset_reports[raw_key]
            p.indicator = indicator
            p.provider = self._name
            return p

        # Default clean / unknown mock response
        return ThreatIntelligenceReport(
            indicator=indicator,
            provider=self._name,
            status=IntelligenceStatus.AVAILABLE,
            verdict=self.default_verdict,
            confidence=self.confidence,
            categories=["mock_threat"] if self.default_verdict in (IntelligenceVerdict.MALICIOUS, IntelligenceVerdict.SUSPICIOUS) else [],
            freshness=FreshnessState.RECENT,
            details={"mock_source": True, "note": "Generated by mock intelligence provider."},
        )
