"""
ScamBuster Heuristic Cyber Analyzer — Phone & Caller Scam Analysis

Deterministic cybersecurity analysis detecting:
- ITU-T E.164 format and digit anomalies
- High-risk Wangiri (one-ring scam) international dialing codes
- Spoofed/synthetic number patterns (sequential/repeating digits)
- Toll-free number cold-calling impersonation
- Impersonation context heuristics (IRS, SSA, Bank fraud alerts)
"""

import re
from typing import Any, Dict, List, Optional

# High-risk international prefixes frequently associated with Wangiri / toll-fraud rings
WANGIRI_HIGH_RISK_CODES = {
    "+232": "Sierra Leone",
    "+223": "Mali",
    "+247": "Ascension Island",
    "+248": "Seychelles",
    "+252": "Somalia",
    "+260": "Zambia",
    "+263": "Zimbabwe",
    "+675": "Papua New Guinea",
    "+676": "Tonga",
    "+678": "Vanuatu",
    "+881": "Global Mobile Satellite System",
    "+882": "International Networks",
    "+883": "International Networks",
    "+231": "Liberia",
    "+235": "Chad",
    "+237": "Cameroon",
    "+238": "Cape Verde",
}

TOLL_FREE_PREFIXES = {"800", "888", "877", "866", "855", "844", "833"}

SUSPICIOUS_CALLER_CONTEXTS = [
    r"\b(irs|internal revenue|tax agent|arrest warrant)\b",
    r"\b(social security|ssa|badge number|federal officer)\b",
    r"\b(refund department|cancel subscription|geek squad|norton)\b",
    r"\b(wire transfer|gift card|crypto atm|western union)\b",
    r"\b(visa fraud|mastercard fraud|bank fraud division)\b",
]


def analyze_phone(phone_number: str, context: Optional[str] = None) -> Dict[str, Any]:
    """
    Perform deep deterministic cybersecurity analysis on phone numbers and caller intent.
    Returns heuristic score (0-100), threat indicators, and telecom metadata.
    """
    clean_num = re.sub(r"[\s\-\(\)\.]", "", phone_number.strip())
    indicators: List[Dict[str, Any]] = []
    score = 0

    # Ensure starts with + if has international representation
    normalized = clean_num if clean_num.startswith("+") else ("+" + clean_num if clean_num.isdigit() and len(clean_num) > 10 else clean_num)

    # 1. High-Risk Wangiri Prefix Check
    for prefix, country in WANGIRI_HIGH_RISK_CODES.items():
        if normalized.startswith(prefix):
            score += 45
            indicators.append({
                "name": f"High-Risk One-Ring (Wangiri) Country Code: {country}",
                "severity": "CRITICAL",
                "description": f"The number originates from {country} ({prefix}), a jurisdiction disproportionately targeted by international toll fraud and Wangiri robocall callbacks.",
                "evidence": f"Prefix {prefix} ({country})",
            })
            break

    # 2. Obvious Spoofed or Repeated Digit Patterns
    digits_only = re.sub(r"\D", "", clean_num)
    if digits_only:
        # Repeating identical digits (e.g. 9999999999)
        if len(set(digits_only)) <= 2 and len(digits_only) >= 7:
            score += 35
            indicators.append({
                "name": "Synthetic / Spoofed Caller ID Pattern",
                "severity": "HIGH",
                "description": "The number consists of repetitive or placeholder digits, indicative of VoIP caller ID spoofing.",
                "evidence": clean_num,
            })
        # Sequential digits (e.g. 1234567890)
        elif "123456" in digits_only or "987654" in digits_only:
            score += 30
            indicators.append({
                "name": "Sequential Caller ID Pattern",
                "severity": "HIGH",
                "description": "The phone number follows a sequential numerical pattern frequently generated by auto-dialer spoofing software.",
                "evidence": clean_num,
            })

    # 3. Toll-Free Impersonation Vector
    # North American Toll-Free format check: +1 800... or 800...
    is_toll_free = False
    if normalized.startswith("+1") and len(normalized) >= 5 and normalized[2:5] in TOLL_FREE_PREFIXES:
        is_toll_free = True
    elif len(clean_num) >= 3 and clean_num[:3] in TOLL_FREE_PREFIXES:
        is_toll_free = True

    if is_toll_free:
        score += 15
        indicators.append({
            "name": "Toll-Free Inbound Service Number",
            "severity": "LOW",
            "description": "Toll-free numbers are legitimate for incoming customer support but frequently forged by scammers in outbound cold-call campaigns.",
            "evidence": f"Toll-free prefix detected in {clean_num}",
        })

    # 4. Contextual Impersonation Analysis (if caller context is provided)
    if context:
        context_lower = context.lower()
        for pattern in SUSPICIOUS_CALLER_CONTEXTS:
            match = re.search(pattern, context_lower)
            if match:
                score += 35
                indicators.append({
                    "name": "High-Risk Impersonation Context",
                    "severity": "HIGH",
                    "description": f"The caller context references high-pressure imposter scam themes: '{match.group(0)}'.",
                    "evidence": match.group(0),
                })
                break

    # 5. Invalid Digit Length (ITU-T E.164 stipulates max 15 digits)
    if len(digits_only) < 7 or len(digits_only) > 15:
        score += 20
        indicators.append({
            "name": "Non-Standard ITU-T Digit Length",
            "severity": "MEDIUM",
            "description": f"The number contains {len(digits_only)} digits, violating standard international telephony specifications (7-15 digits).",
            "evidence": f"Length: {len(digits_only)} digits",
        })

    capped_score = min(max(score, 0), 100)

    return {
        "score": capped_score,
        "indicators": indicators,
        "details": {
            "normalized_number": normalized,
            "digit_count": len(digits_only),
            "is_toll_free": is_toll_free,
            "has_context": bool(context),
            "indicator_count": len(indicators),
        }
    }
